// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Fullscreen","status":false,"description":"Starts the game in fullscreen","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"1920","screenHeight":"1080","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}}
];
